pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git branch: 'pipelinefiles',
                credentialsId: '622c639f-ceeb-4737-8233-1a42f1b5275f',
                url: 'https://github.com/sangavipriya20/JenkinsCICD.git'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t samoan123/cicd-e2e:${BUILD_NUMBER} python-jenkins-argocd-k8s/
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push samoan123/cicd-e2e:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git branch: 'main',
                credentialsId: '622c639f-ceeb-4737-8233-1a42f1b5275f',
                url: 'https://github.com/sangavipriya20/cicd-k8s-manifest-repo.git'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: '622c639f-ceeb-4737-8233-1a42f1b5275f', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        cat deploy.yaml
                        sed -i '' "s/32/${BUILD_NUMBER}/g" deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/sangavipriya20/cicd-k8s-manifest-repo.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}